### ISSUE TITLE
malformed author info on pypi and napari hub

### ISSUE THREAD

**Issue by neuromusic** [campaslab/napari-stress#205]
Hello!!

Congrats on your recent release of napari-stress :D

Unfortunately, there seems to be something off with your author info.

On the napari hub: https://www.napari-hub.org/plugins/napari-stress

![image](https://user-images.githubusercontent.com/1245615/200674982-6c9fd05e-51a0-4e13-be1e-770ed51e6f18.png)

On PyPI: https://pypi.org/project/napari-stress/

![image](https://user-images.githubusercontent.com/1245615/200675248-079c3126-5eaf-48ca-b3d6-88873a424105.png)

Its not clear to me where the problem is since your setup.cfg looks fine 🤔 

https://github.com/BiAPoL/napari-stress/blob/main/setup.cfg#L4

**Comment by neuromusic** [comment]
looks like it will also affect this plugin on @haesleinhuepf 's ["Dresden" collection](https://staging.napari-hub.org/collections/dresden) when it launches next week:

<img width="898" alt="image" src="https://user-images.githubusercontent.com/1245615/200926698-2f53ebd9-5823-4eac-abdb-ad94f5109856.png">

**Comment by haesleinhuepf** [comment]
Hint: It's possible to have an ü in the name as shown here: https://staging.napari-hub.org/plugins/napari-stl-exporter 

Maybe, the encoding of setup.py is just confused?

**Comment by jo-mueller** [comment]
Hi @neuromusic ,

thanks for flagging this. Maybe it's the combination of multiple authors and special characters? In the napari-stl-exporter it seems to work, but I'm also the sole author there. A cheap fix could be to just spell my name differently (e.g., Mueller instead of Müller, which is a common thing to do on non-german keyboards)

**Comment by haesleinhuepf** [comment]
Hi @jo-mueller ,

can you revisit this issue? The napari-hub page really looks not good these days. 

![image](https://user-images.githubusercontent.com/12660498/213923148-858dd896-5e71-44db-a0d3-84b2f37580e9.png)

Maybe check if authors changed their lastname, update the list and publish a new release to pypi.

Thanks!

**Comment by jo-mueller** [comment]
Accidentally closed this. Has been fixed by PR #227 , but somehow automatic deployment failed.

**Comment by jo-mueller** [comment]
Fixed this in latest release 0.1.5. Thanks again for reporting!
