### ISSUE TITLE
Issue with pygeodesic installation on Mac M1

### ISSUE THREAD

**Issue by haesleinhuepf** [campaslab/napari-stress#207]
Hi  Johannes @jo-mueller ,

there is a discussion about [installation of napari-stress on image.sc](https://forum.image.sc/t/napari-stress-problem-loading-some-dependancies/73758/5?u=haesleinhuepf). Apparently, pygeodesic cannot be installed on Mac M1. Do you have experience with this? If so, could you respond on image.sc and update the installation instructions accordingly?

Alternatively: could pygeodesic be replaced by something else? Or is it a key-dependency?

Thanks!

Best,
Robert

**Comment by jo-mueller** [comment]
Thanks @haesleinhuepf for flagging this. I *think* there are a bunch of other, similar packages. I know it's possible with PyVista (haven't tried it yet, it's also a huge dependency) and I like the slim syntax of `pygeodesics`. There is also [gdist](https://github.com/the-virtual-brain/tvb-gdist) which is the more raw version of pygeodesics and seems a bit more actively maintained.
