### ISSUE TITLE
Put Point cloud smoothing in the right menu

### ISSUE THREAD

**Issue by haesleinhuepf** [campaslab/napari-stress#224]
I presume the menu `Tools > Surfaces > Smoothing (MLS2D, vedo, n-STRESS)` should be under `Tools > Points` because it processes points and not surfaces:

https://github.com/campaslab/napari-stress/blob/4ad2704373935dd242b0ada09793e7a4eb1abe93/src/napari_stress/_surface.py#L139-L143

**Comment by jo-mueller** [comment]
Hi @haesleinhuepf ,

I don't think this function should be here in the first place. Would you mind if I sent it as a PR to napari-process-points-and-surfaces?

**Comment by haesleinhuepf** [comment]
Yes, great idea! Consider using the opportunity to give the function a better name. 😉

**Comment by jo-mueller** [comment]
Good idea^^ I'll close this issue here and open one at nppas - there are actually a few functions that would be nice to have.
