### ISSUE TITLE
Update documentation to not mention open3d anymore

### ISSUE THREAD

**Issue by haesleinhuepf** [campaslab/napari-stress#226]
When [searching the documentation of napari-stress for "open3d"](https://github.com/campaslab/napari-stress/search?q=open3d), I found two places, where the open3d-dependent version of napari-process-points-and-surfaces is used:

* [ ] https://github.com/campaslab/napari-stress/blob/4ad2704373935dd242b0ada09793e7a4eb1abe93/docs/03_workflows/Image_to_surface.md
* [ ] https://github.com/campaslab/napari-stress/blob/4ad2704373935dd242b0ada09793e7a4eb1abe93/docs/03_workflows/Surface_to_curvature.md

The mentioned menus `Tools > Surfaces > Smoothing (Laplacian, open3d, nppas)` and `Tools > Points > Create points from surface using poisson disk sampling (open3d, nppas)` **will be removed from napari-process-points-and-surfaces** in the next release. See also:
* https://github.com/haesleinhuepf/napari-process-points-and-surfaces/pull/23

Thus, we should update the documentation of napari-stress to keep workflows functional. I presume the new menus are:
`Tools > Surfaces > Smooth (vedo, nppas)` and `Tools > Points > Create points from surface (vedo, nppas)`. However, I haven't tested and I'm afraid the results will look different from the functions before. Agian, we need to carefully check and update the documentation accordingly.

**Comment by jo-mueller** [comment]
Thanks for pointing this out. There's three more locations where this is the case in the codebase:

- [Here](https://github.com/campaslab/napari-stress/blob/97f0e1c3153b5d1ec0997b69d4ec936735783512/src/napari_stress/_surface.py#L172) (this function can be deprecated anyway.
- [Here](https://github.com/campaslab/napari-stress/blob/97f0e1c3153b5d1ec0997b69d4ec936735783512/src/napari_stress/_reconstruction/toolbox.py#L149]
- [Here](https://github.com/campaslab/napari-stress/blob/97f0e1c3153b5d1ec0997b69d4ec936735783512/src/napari_stress/_reconstruction/toolbox.py#L152)

**Comment by haesleinhuepf** [comment]
napari-process-points-and-surfaces 0.4.0 has been released. It does not depend on open3d anymore and menus have been moved. Read details here:
https://github.com/haesleinhuepf/napari-process-points-and-surfaces/releases/tag/0.4.0
