### ISSUE TITLE
project intensity on surface

### ISSUE THREAD

**Issue by JanaFuhrmann** [campaslab/napari-stress#280]
It would be cool if it where possible to measure intensities along normal vectors and project on a previously defined surface.
Ideally it would also be documented :)

**Comment by jo-mueller** [comment]
Hi  @JanaFuhrmann ,

this feature has been added in napari-stress 0.2.7 :) In the napari-viewer, you'll find it under `Tools > Measurement > Measure intensity on surface`, from code you could calll it like

```python
from napari_stress import measurements

measurements.measure_intensity_on_surface(...)
```

Let me know whether that's useful for you :)
