### ISSUE TITLE
Export reconstructions and graphs from napari? 

### ISSUE THREAD

**Issue by elena-scarpa** [campaslab/napari-stress#299]
Hi Johannes,

I have been going through the analysis again with a control dataset. reconstructions look good so far. I have realised I have not asked you whether and how I save the analysis, so that I can go back to it at any point? which format  should I use? can I export reconstructions and quantifications as figures? I understand I can export the stress measurements as CSV?
thanks a lot!
Elena

**Comment by jo-mueller** [comment]
Hi @elena-scarpa ,

I just published napari-stress 0.2.8 which has the feature of exporting plots. This should already make your life a bit easier regarding getting your hands on the actual data :)

**Comment by jo-mueller** [comment]
@elena-scarpa I'll close this as this is part of napari-stress since a few versions.
