### ISSUE TITLE
'FeaturesHistogramWidget' object has no attribute 'x_axis_key'

### ISSUE THREAD

**Issue by elena-scarpa** [campaslab/napari-stress#316]
Hi Johannes,

I have been trying to reconstruct a few old and new droplets.
I had a big improvement when imaging the drops using a confocal with 25xWater immersion lens.  
Reconstruction is not perfect looks good enough (to me)
![e1_droplet1_ss5](https://github.com/campaslab/napari-stress/assets/127401980/6edd97d3-18e9-4831-886a-11613ad9e4a3)
 
I did the next step of stress measurements, which I can visualise graphically on the droplet reconstructions:
![e1_droplet1_ss5_stresses3D](https://github.com/campaslab/napari-stress/assets/127401980/25522507-12aa-4f48-9219-527aedb69865)

However I currently have an error message on the data visualisation widget (Tools>Visualization>Visualise point cloud features): 
![Screenshot 2023-07-24 at 11 45 41](https://github.com/campaslab/napari-stress/assets/127401980/de6788c1-754d-46f9-b2fd-07645eddcd10)

and if I press "view traceback" I get this code below. Any way you could help me fixing the issue? I tried several different droplets and I still get the issue, so it doesn't seem to be linked with the data...

code (to be debugged?) below:
thanks a lot, 
Elena

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
File ~/mambaforge/envs/droplets/lib/python3.9/site-packages/napari_tools_menu/__init__.py:83, in ToolsMenu.make_sub_sub_menu.<locals>.func(whatever=False)
     78             break
     79         # cannot look for param.kind == param.VAR_KEYWORD because
     80         # QWidget allows **kwargs but errs on unknown keyword arguments
     81 
     82     # instantiate the widget
---> 83     wdg = action(**kwargs)
        action = <class 'napari_stress._plotting.features_histogram.FeaturesHistogramWidget'>
        kwargs = {'napari_viewer': Viewer(camera=Camera(center=(79.0, 66.5, 70.5), zoom=9.638526318598242, angles=(11.432494202491071, -34.01097324546466, 50.419498807042096), perspective=0.0, mouse_pan=True, mouse_zoom=True), cursor=Cursor(position=(0.0, 44.459712936408394, 86.32670549372708, 91.23012294394077), scaled=True, size=1, style=<CursorStyle.STANDARD: 'standard'>), dims=Dims(ndim=4, ndisplay=3, last_used=0, range=((0.0, 1.0, 1.0), (0.0, 159.0, 0.4545), (-0.27275, 133.72725, 0.4545), (-0.27275, 141.72725, 0.4545)), current_step=(0, 87, 66, 70), order=(0, 1, 2, 3), axis_labels=('0', '1', '2', '3')), grid=GridCanvas(stride=-1, shape=(-1, -1), enabled=False), layers=[<Image layer 'rotated_ e1_2droplets_trunkss5_18hpf-droplet1_ss' at 0x179f724f0>, <Image layer 'Rescaled image' at 0x17a7b80a0>, <Labels layer 'Label image' at 0x179fc9be0>, <Points layer 'points_first_guess' at 0x17c42d610>, <Points layer 'Refined_points' at 0x17a902fd0>, <Vectors layer 'Normals' at 0x17bcfce80>, <Points layer 'Center' at 0x17bdd6550>, <Points layer 'Result of fit spherical harmonics (deg = 21' at 0x17bf37e20>, <Points layer 'Result of expand points on ellipsoid' at 0x176e9d520>, <Vectors layer 'Result of least squares ellipsoid' at 0x176e5f8e0>, <Points layer 'Result of lebedev quadrature on ellipsoid' at 0x177f438b0>, <Points layer 'Result of lebedev quadrature (droplet)' at 0x176ecffd0>, <Points layer 'Extrema total stress' at 0x179d4b670>, <Points layer 'Extrema cell stress' at 0x179ea4cd0>, <Vectors layer 'Total stress: Geodesics maxima -> nearest minima' at 0x17c22aa00>, <Vectors layer 'Total stress: Geodesics minima -> nearest maxima' at 0x179e61850>, <Vectors layer 'Cell stress: Geodesics maxima -> nearest minima' at 0x17fec6760>, <Vectors layer 'Cell stress: Geodesics minima -> nearest maxima' at 0x17ffed070>, <Surface layer 'stress_autocorrelations' at 0x1801ec820>], help='use <5> for transform, use <2> for add points, use <3> for select points', status={'layer_base': 'Result of lebedev quadrature (droplet)', 'source_type': '', 'plugin': '', 'coordinates': ' [44 86 91]'}, tooltip=Tooltip(visible=False, text=''), theme='dark', title='napari', mouse_over_canvas=True, mouse_move_callbacks=[], mouse_drag_callbacks=[], mouse_double_click_callbacks=[], mouse_wheel_callbacks=[<function dims_scroll at 0x14bd7f820>], _persisted_mouse_event={}, _mouse_drag_gen={}, _mouse_wheel_gen={}, keymap={})}
     84     dw = napari_viewer.window.add_dock_widget(wdg, name=title)
     85 if dw is not None:
     86     # workaround for https://github.com/napari/napari/issues/4348

File ~/mambaforge/envs/droplets/lib/python3.9/site-packages/napari_stress/_plotting/features_histogram.py:33, in FeaturesHistogramWidget.__init__(self=<napari_stress._plotting.features_histogram.FeaturesHistogramWidget object>, napari_viewer=Viewer(camera=Camera(center=(79.0, 66.5, 70.5), ...ouse_drag_gen={}, _mouse_wheel_gen={}, keymap={}))
     32 def __init__(self, napari_viewer: napari.viewer.Viewer):
---> 33     super().__init__(napari_viewer)
        napari_viewer = Viewer(camera=Camera(center=(79.0, 66.5, 70.5), zoom=9.638526318598242, angles=(11.432494202491071, -34.01097324546466, 50.419498807042096), perspective=0.0, mouse_pan=True, mouse_zoom=True), cursor=Cursor(position=(0.0, 44.459712936408394, 86.32670549372708, 91.23012294394077), scaled=True, size=1, style=<CursorStyle.STANDARD: 'standard'>), dims=Dims(ndim=4, ndisplay=3, last_used=0, range=((0.0, 1.0, 1.0), (0.0, 159.0, 0.4545), (-0.27275, 133.72725, 0.4545), (-0.27275, 141.72725, 0.4545)), current_step=(0, 87, 66, 70), order=(0, 1, 2, 3), axis_labels=('0', '1', '2', '3')), grid=GridCanvas(stride=-1, shape=(-1, -1), enabled=False), layers=[<Image layer 'rotated_ e1_2droplets_trunkss5_18hpf-droplet1_ss' at 0x179f724f0>, <Image layer 'Rescaled image' at 0x17a7b80a0>, <Labels layer 'Label image' at 0x179fc9be0>, <Points layer 'points_first_guess' at 0x17c42d610>, <Points layer 'Refined_points' at 0x17a902fd0>, <Vectors layer 'Normals' at 0x17bcfce80>, <Points layer 'Center' at 0x17bdd6550>, <Points layer 'Result of fit spherical harmonics (deg = 21' at 0x17bf37e20>, <Points layer 'Result of expand points on ellipsoid' at 0x176e9d520>, <Vectors layer 'Result of least squares ellipsoid' at 0x176e5f8e0>, <Points layer 'Result of lebedev quadrature on ellipsoid' at 0x177f438b0>, <Points layer 'Result of lebedev quadrature (droplet)' at 0x176ecffd0>, <Points layer 'Extrema total stress' at 0x179d4b670>, <Points layer 'Extrema cell stress' at 0x179ea4cd0>, <Vectors layer 'Total stress: Geodesics maxima -> nearest minima' at 0x17c22aa00>, <Vectors layer 'Total stress: Geodesics minima -> nearest maxima' at 0x179e61850>, <Vectors layer 'Cell stress: Geodesics maxima -> nearest minima' at 0x17fec6760>, <Vectors layer 'Cell stress: Geodesics minima -> nearest maxima' at 0x17ffed070>, <Surface layer 'stress_autocorrelations' at 0x1801ec820>], help='use <5> for transform, use <2> for add points, use <3> for select points', status={'layer_base': 'Result of lebedev quadrature (droplet)', 'source_type': '', 'plugin': '', 'coordinates': ' [44 86 91]'}, tooltip=Tooltip(visible=False, text=''), theme='dark', title='napari', mouse_over_canvas=True, mouse_move_callbacks=[], mouse_drag_callbacks=[], mouse_double_click_callbacks=[], mouse_wheel_callbacks=[<function dims_scroll at 0x14bd7f820>], _persisted_mouse_event={}, _mouse_drag_gen={}, _mouse_wheel_gen={}, keymap={})
     34     self._key_selection_widget = magicgui(
     35         self._set_axis_keys,
     36         x_axis_key={"choices": self._get_valid_axis_keys},
     37         n_bins={"value": 50, "widget_type": "SpinBox"},
     38         call_button="Update",
     39     )
     40     self._export_button = magicgui(
     41         self.export,
     42         call_button='Export plot as csv'
     43         )

File ~/mambaforge/envs/droplets/lib/python3.9/site-packages/napari_matplotlib/histogram.py:29, in HistogramWidget.__init__(self=<napari_stress._plotting.features_histogram.FeaturesHistogramWidget object>, napari_viewer=Viewer(camera=Camera(center=(79.0, 66.5, 70.5), ...ouse_drag_gen={}, _mouse_wheel_gen={}, keymap={}), parent=None)
     23 def __init__(
     24     self,
     25     napari_viewer: napari.viewer.Viewer,
     26     parent: Optional[QWidget] = None,
     27 ):
     28     super().__init__(napari_viewer, parent=parent)
---> 29     self._update_layers(None)
        self = <napari_stress._plotting.features_histogram.FeaturesHistogramWidget object at 0x180569d30>

File ~/mambaforge/envs/droplets/lib/python3.9/site-packages/napari_matplotlib/base.py:248, in NapariMPLWidget._update_layers(self=<napari_stress._plotting.features_histogram.FeaturesHistogramWidget object>, event=None)
    246 self.layers = sorted(self.layers, key=lambda layer: layer.name)
    247 self.on_update_layers()
--> 248 self._draw()
        self = <napari_stress._plotting.features_histogram.FeaturesHistogramWidget object at 0x180569d30>

File ~/mambaforge/envs/droplets/lib/python3.9/site-packages/napari_matplotlib/base.py:262, in NapariMPLWidget._draw(self=<napari_stress._plotting.features_histogram.FeaturesHistogramWidget object>)
    258     self.clear()
    259 if self.n_selected_layers in self.n_layers_input and all(
    260     isinstance(layer, self.input_layer_types) for layer in self.layers
    261 ):
--> 262     self.draw()
        self = <napari_stress._plotting.features_histogram.FeaturesHistogramWidget object at 0x180569d30>
    263 self.canvas.draw()

File ~/mambaforge/envs/droplets/lib/python3.9/site-packages/napari_stress/_plotting/features_histogram.py:282, in FeaturesHistogramWidget.draw(self=<napari_stress._plotting.features_histogram.FeaturesHistogramWidget object>)
    280 def draw(self) -> None:
    281     """Clear the axes and histogram the currently selected layer/slice."""
--> 282     data, x_axis_name, y_axis_name = self._get_data()
        self = <napari_stress._plotting.features_histogram.FeaturesHistogramWidget object at 0x180569d30>
    284     if len(data) == 0:
    285         # don't plot if there isn't data
    286         return

File ~/mambaforge/envs/droplets/lib/python3.9/site-packages/napari_stress/_plotting/features_histogram.py:178, in FeaturesHistogramWidget._get_data(self=<napari_stress._plotting.features_histogram.FeaturesHistogramWidget object>)
    172     return [], "", ""
    174 feature_table = self.layers[0].features
    176 if (
    177     (len(feature_table) == 0)
--> 178     or (self.x_axis_key is None)
        feature_table =      mean_curvature  difference_mean_curvature_cartesian_radial_manifold  ...  anisotropic_stress  anisotropic_stress_total_radial
0          0.024185                                           1.103333    ...           -0.251928                        -0.606785
1          0.016474                                           1.103333    ...           -0.344463                        -0.609252
2          0.085415                                           1.103333    ...            0.482835                        -0.094868
3          0.059158                                           1.103333    ...            0.167747                        -0.105767
4          0.052521                                           1.103333    ...            0.088101                        -0.062657
..              ...                                                ...    ...                 ...                              ...
585        0.062178                                           1.103333    ...            0.203989                        -0.375438
586        0.046580                                           1.103333    ...            0.016819                        -0.351163
587        0.183218                                           1.103333    ...            1.656466                        -0.042477
588        0.045432                                           1.103333    ...            0.003035                        -0.182165
589        0.013707                                           1.103333    ...           -0.377661                         0.314791

[590 rows x 5 columns]
        self = <napari_stress._plotting.features_histogram.FeaturesHistogramWidget object at 0x180569d30>
    179 ):
    180     return [], "", 0
    182 data_x = feature_table[self.x_axis_key]

AttributeError: 'FeaturesHistogramWidget' object has no attribute 'x_axis_key'

**Comment by elena-scarpa** [comment]
Without the data visualisation widget working I can't plot the data and see whether they make any sense or not....

**Comment by jo-mueller** [comment]
Hi @elena-scarpa ,

I looked at it and using a different version of napari-matplotlib solves the issue. To use it, install it like this in your environment:

```bash
pip install napari-matplotlib==0.2.0
```

**Comment by elena-scarpa** [comment]
Thanks!!
I guess I can keep the current version of napari-stress on top?

Cheers
E.


Dr Elena Scarpa (she/her)
Dorothy Hodgkin Research Fellow
-----------------------------------------------
Department of Physiology, Development and Neuroscience
Anatomy Building, Downing Street
Cambridge CB2 3DY
***@***.***


From: Johannes Soltwedel ***@***.***>
Date: Monday, 14 August 2023 at 11:49
To: campaslab/napari-stress ***@***.***>
Cc: Elena Scarpa ***@***.***>, Mention ***@***.***>
Subject: Re: [campaslab/napari-stress] 'FeaturesHistogramWidget' object has no attribute 'x_axis_key' (Issue #316)

Hi @elena-scarpa<https://github.com/elena-scarpa> ,

I looked at it and using a different version of napari-matplotlib solves the issue. To use it, install it like this in your environment:

pip install napari-matplotlib==0.2.0

**Comment by jo-mueller** [comment]
Hi @elena-scarpa ,

PR #330 should fix this. In the next version (which I'll release shortly), you can use the napari-matplotlib plugin to get the same kind of visualization. I updated the documentation to account for the changes.
