### ISSUE TITLE
Error if reconstruction interpolation set to cubic

### ISSUE THREAD

**Issue by jo-mueller** [campaslab/napari-stress#366]
Analyze-everything notebook throws error if interpolation set to `cubic`

![image](https://private-user-images.githubusercontent.com/102696383/321611237-1757f770-f4a6-4eaf-b996-908df86724c6.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4Mzg3NjgsIm5iZiI6MTcxMjgzODQ2OCwicGF0aCI6Ii8xMDI2OTYzODMvMzIxNjExMjM3LTE3NTdmNzcwLWY0YTYtNGVhZi1iOTk2LTkwOGRmODY3MjRjNi5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxMVQxMjI3NDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04OWUyMTdlMzljOGI2ZDllZjAxMTlhNTRhOWQ5NWEwM2I1YzcyYThmYjU1YjIyNTAwNmNmY2Y4MDg0MmQ3MDFjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.2VQ2wJeESgGevtoFHBIY_lkjUmtOzjFuCgJtX7YtHfI)

@carlos-gomez00

**Comment by carlos-gomez00** [comment]
It returned 0.3.3, I updated before using the notebook using pip install napari-stress --upgrade

**Comment by jo-mueller** [comment]
@carlos-gomez00 ok that's strange...can you check which scipy version you have?

**Comment by carlos-gomez00** [comment]
@jo-mueller When I checked the environment it gave this out: scipy                     1.8.1            py39h5567194_2    conda-forge

I have also attached the parameters I had when running the Notebook

![Parameters](https://github.com/campaslab/napari-stress/assets/102696383/980003cb-5e8c-493a-a642-b0f1c67a9142)

**Comment by jo-mueller** [comment]
Can you try upgrading scipy to something newer? On my PC, I have scipy `1.13.0`.
You could do mamba install `scipy==1.13.0`

**Comment by carlos-gomez00** [comment]
@jo-mueller I have upgraded it and it hasn't crashed, but I think due to the size of the data (it had 25 time points)

This is what it's outputting, if it doesn't finish in an hour I'll restart and try with a smaller stack.

![Line11Error](https://github.com/campaslab/napari-stress/assets/102696383/11010819-e6b1-44eb-b8f1-5f47fe622230)

**Comment by jo-mueller** [comment]
@carlos-gomez00 try increasing the resampling length (i think that's what the parameter waa called) a bit. Lower numbers lead to a bazillion of points to be reconstructed on the droplet, which for cubic interpolation drives the compute requirements skyhigh. 

A safe bet could be resampling length =10. Also depends a bit on the resolution of the data.

**Comment by carlos-gomez00** [comment]
@jo-mueller I have changed the re-sampling length and it still gives out the errors as before, I have even cut the timelapse data to 3 time points

**Comment by jo-mueller** [comment]
@carlos-gomez00 hm...how large is the data, in general?

**Comment by carlos-gomez00** [comment]
@jo-mueller It was 84 MB (three timepoints) he original data was 700 MB (25 time points)

**Comment by jo-mueller** [comment]
@carlos-gomez00 Ok, that shouldn't be too much...what were the input voxel sizes and to what was the target voxelsize set?

**Comment by carlos-gomez00** [comment]
@jo-mueller The x and y was 0.5535106 and Z was 1.1842999. I used 0.5535106 as the target voxel size since I saw the x value was used as the target voxel size in the sample data

**Comment by jo-mueller** [comment]
Hi @carlos-gomez00 ,

I just tried it with your data and got the following results in <5min.  I used these settings for the dimensions

```python
voxel_size_x = 0.55  # microns
voxel_size_y = 0.55  # microns
voxel_size_z = 1.18  # microns
target_voxel_size = 1  # microns
time_step = 3  # minutes
```

... and these for the reconstruction

```python
reconstruction_parameters = {
    'voxelsize': np.asarray([voxel_size_z, voxel_size_y, voxel_size_x]),
    'target_voxelsize': target_voxel_size,
    'smoothing_sigma': 1,
    'n_smoothing_iterations': 15,
    'n_points': 256,
    'n_tracing_iterations': 1,
    'resampling_length': 1,
    'fit_type': 'fancy',   # can be 'fancy' or 'quick'
    'edge_type': 'interior',   # can be 'interior' or 'surface'
    'trace_length': 20,
    'sampling_distance': 0.5,
    'interpolation_method':  'linear',  # can be 'linear' 'cubic' or 'nearest'
    'outlier_tolerance': 1.5,
    'remove_outliers': True,
    'return_intermediate_results': True}

measurement_parameters = {
    'max_degree': 20,  # spherical harmonics degree
    'n_quadrature_points': 5810,  # number of quadrature points to measure on (maximum is 5810)
    'gamma': 3.3}  # interfacial tension of droplet
alpha = 0.05  # lower and upper boundary in cumulative distribution function which should be used to calculate the stress anisotropy
```

Can you confirm whether this does or doesn't work on your end?

![output](https://github.com/campaslab/napari-stress/assets/38459088/62689df2-550a-4686-86b7-13bfc09868fe)

**Comment by jo-mueller** [comment]
I also just released a new vversion (`napari-stress==0.3.4`) that constraints the necessary packages to the correct version to make sure `cubic` interpolation is available (wasn't available in scipy before `1.9`).

**Comment by carlos-gomez00** [comment]
Hi @jo-mueller I just tried the previous parameters with napari-stress 0.3.3 and it did work, but after updating to 0.3.5 and running the same parameters, it was able to do the reconstruction, but stopped at the analysis portion
![ErrorAfterUpdate](https://github.com/campaslab/napari-stress/assets/102696383/23c7d715-2427-4fe3-8131-05f6e29bb220)

**Comment by jo-mueller** [comment]
Hi @carlos-gomez00 , sorry - that's something I need to fix. 

In the cell that throws the error, try the following:

```python
results_stress_analysis = measurements. comprehensive_analysis(input_data, **measurement_parameters, use_dask=parallelize)
```

**Comment by carlos-gomez00** [comment]
@jo-mueller No worries, unfortunately it still gave the same error :0
![ErrorReplacingCode](https://github.com/campaslab/napari-stress/assets/102696383/7680c165-b52c-41cb-926e-a6d82cf082b7)

**Comment by jo-mueller** [comment]
Ah, shoot. The line before trues to retrieve the data from the napari layer, which as it seems is not called `points_patch_fitted` but something else. You'd have to check in the viewer, the layer is probably called something like `pointcloud (smoothed)` or something

**Comment by carlos-gomez00** [comment]
@jo-mueller Got it, I changed it to what I think is the correct one Droplet pointcloud (smoothed), no error this time, but it's taking much longer than usual
![Timer](https://github.com/campaslab/napari-stress/assets/102696383/e41ce6e3-3d74-4496-a6c3-d7973ca100ef)

**Comment by jo-mueller** [comment]
Depending on what number of lebedev points is set further up it will be at least an hour until you see the first sign of progress on the dashboard :)

**Comment by carlos-gomez00** [comment]
@jo-mueller It worked! It did take about 1.5 hrs, but it finished throught the whole notebook, thanks!
