### ISSUE TITLE
Analyze-deluxe

### ISSUE THREAD

**Issue by haesleinhuepf** [campaslab/napari-stress#80]
Mid/long-term it would be cool if we had a python function that does everything in one shot. It would be the Python-equivalent for [`AnalyzeDeluxe3D.m`](https://github.com/campaslab/STRESS/blob/main/AnalyzeDeluxe3D.m)

I presume this function has those parameters:

```
image: np.ndarray
voxel_size_xy: float = 1
voxel_size_z: float = 1
droplet_edge_labeled: bool = False
interfractial_tension: float = 1
edge_detection = quick_edge_detection #not sure what type, Enum of Callable?
parallelize : bool = False
gaussian_filter_sigma : float = 1
fidelity : FidelityEnum = FidelityEnum.Bottom_of_the_barrel
maximize_num_lebedev_points : bool = False
alpha : float = 0.5
reference_coordinates = None
```

If we had that function, we could easily run the published algorithm with different parameters and compare results.

**Comment by jo-mueller** [comment]
Hi @haesleinhuepf ,

I think this is a great idea. I was considering putting all measurements into separate functions (see #27) but as they are deeply intertwined in how they are generated, I think it may make more sense to put them into a single measurement widget.

I think I would still create two separate toolbox widgets: One for surface reconstruction (Rescaling -> Binarization -> marching cubes-> smoothing -> trace-refinement) and another one for spherical harmonics and all that stuff that comes out of this

**Comment by haesleinhuepf** [comment]
> putting all measurements into separate functions

If possible, I would put independent things in independent functions. One can then combine the functions in a user-friendly widget. I suggest drawing relationships between stuff on a white board 😉

**Comment by jo-mueller** [comment]
I started working on something towards that in [this branch](https://github.com/BiAPoL/napari-stress/tree/comprehensive-spherical-harmonics-toolbox).

I quickly found that I'd need a stronger separation of fron-end functions (e.g., those that are exposed to napari) and "engine-room" functions that do all the fancy stuff under the hood. That makes it easier to pick parts of the stress-functionality and make it available as widgets.

I did quite a bit of re-arranging of code on this branch - I'm thinking of starting a PR with these changes alone, what do you think @haesleinhuepf ?

**Comment by jo-mueller** [comment]
![screenshot](https://user-images.githubusercontent.com/38459088/176496626-069c70c7-1f1d-46b6-a5f8-2605715c032d.png)

This would be my first take on how this could look like. Hope you like it :) (Yes, the plots updates if you slide through time 8-) )

**Comment by haesleinhuepf** [comment]
Amazing @jo-mueller ! I recommend sending this as PR before moving ahead

**Comment by jo-mueller** [comment]
Thanks! I'll start a PR then.

I'd maybe also add some generic measurements to the `Shape spectrum` and `Geometry` tab so that they are not blank. I was thinking of putting the power spectrum (e.g., the shape spectrum) into the `Shape spectrum` tab and Volume/surface area into the `geometry`. 

The shape spectrum can be calculated quite straight-forward once #86 is resolved.

**Comment by jo-mueller** [comment]
I'll close this issue - there are toolboxes and example notebooks for analyze-deluxe functionality.
